# Generated by Django 6.0.2 on 2026-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('jobrole', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('dateposted', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
